<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Class_type extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Class_type_model');
        $this->load->library('form_validation');
        if($this->session->userdata('user_login') != 'TRUE'){ redirect('login', 'refresh');}
        if($this->session->userdata('user_level') != '1'){ redirect('login', 'refresh');}
    }

    public function index()
    {
        $class_type = $this->Class_type_model->get_all();

        $data = array(
            'class_type_data' => $class_type
        );

        $this->template->load('template','class_type/class_type_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Class_type_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'name' => $row->name,
        'create_at' => $row->create_at,
        'update_at' => $row->update_at,
	    );
            $this->template->load('template','class_type/class_type_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('class_type'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('class_type/create_action'),
	    'id' => set_value('id'),
	    'name' => set_value('name'),
	);
        $this->template->load('template','class_type/class_type_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
	    );

            $this->Class_type_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('class_type'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Class_type_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('class_type/update_action'),
		'id' => set_value('id', $row->id),
		'name' => set_value('name', $row->name),
	    );
            $this->template->load('template','class_type/class_type_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('class_type'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
        'update_at' => date('Y-m-d H:m:s'),
	    );

            $this->Class_type_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('class_type'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Class_type_model->get_by_id($id);

        if ($row) {
            $this->Class_type_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('class_type'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('class_type'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('name', 'name', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Class_type.php */
/* Location: ./application/controllers/Class_type.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-22 17:23:35 */
/* http://harviacode.com */