<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Classroom extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model(array('Classroom_model','Class_type_model'));
        $this->load->library('form_validation');
        if($this->session->userdata('user_login') != 'TRUE'){ redirect('login', 'refresh');}
        if($this->session->userdata('user_level') != '1'){ redirect('login', 'refresh');}
    }

    public function index()
    {
        $classroom = $this->Classroom_model->get_all();

        $data = array(
            'classroom_data' => $classroom
        );

        $this->template->load('template','classroom/classroom_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Classroom_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'name' => $row->name,
		'quota' => $row->quota,
		'create_at' => $row->create_at,
		'update_at' => $row->update_at,
	    );
            $this->template->load('template','classroom/classroom_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('classroom'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('classroom/create_action'),
    	    'id' => set_value('id'),
    	    'name' => set_value('name'),
    	    'quota' => set_value('quota'),
            // 'class_type_id' => set_value('class_type_id'),
            'get_all_classtype' => $this->Class_type_model->get_all(),
	);
        $this->template->load('template','classroom/classroom_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
    		'name' => $this->input->post('name',TRUE),
    		'quota' => $this->input->post('quota',TRUE),
            'class_type_id' => $this->input->post('class_type_id',TRUE),
	    );

            $this->Classroom_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('classroom'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Classroom_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('classroom/update_action'),
        		'id' => set_value('id', $row->id),
        		'name' => set_value('name', $row->name),
        		'quota' => set_value('quota', $row->quota),
                'class_type_id' => set_value('class_type_id',$row->class_type_id),
                'class_type_name' => set_value('class_type_name',$row->type_name),
                'get_all_classtype' => $this->Class_type_model->get_all(),

	    );
            $this->template->load('template','classroom/classroom_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('classroom'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
    		'name' => $this->input->post('name',TRUE),
    		'quota' => $this->input->post('quota',TRUE),
            'class_type_id' => $this->input->post('class_type_id',TRUE),
    		'update_at' => date('Y-m-d H:i:s'),
	    );

            $this->Classroom_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('classroom'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Classroom_model->get_by_id($id);

        if ($row) {
            $this->Classroom_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('classroom'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('classroom'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('name', 'name', 'trim|required');
	$this->form_validation->set_rules('quota', 'quota', 'trim|required');
    $this->form_validation->set_rules('class_type_id', 'class_type_id', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Classroom.php */
/* Location: ./application/controllers/Classroom.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-22 18:08:58 */
/* http://harviacode.com */