<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Group extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Group_model');
        $this->load->library('form_validation');
        if($this->session->userdata('user_login') != 'TRUE'){ redirect('login', 'refresh');}
        if($this->session->userdata('user_level') != '1'){ redirect('login', 'refresh');}
    }

    public function index()
    {
        $group = $this->Group_model->get_all();

        $data = array(
            'group_data' => $group
        );

        $this->template->load('template','group/group_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Group_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'name' => $row->name,
	    );
            $this->template->load('template','group/group_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(base_url().'group');
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('group/create_action'),
	    'id' => set_value('id'),
	    'name' => set_value('name'),
	);
        $this->template->load('template','group/group_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
	    );

            $this->Group_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(base_url().'group');
        }
    }
    
    public function update($id) 
    {
        $row = $this->Group_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('group/update_action'),
		'id' => set_value('id', $row->id),
		'name' => set_value('name', $row->name),
	    );
            $this->template->load('template','group/group_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(base_url().'group');
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
        'update_at' => date('Y-m-d H:i:s'),
	    );

            $this->Group_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(base_url().'group');
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Group_model->get_by_id($id);

        if ($row) {
            $this->Group_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(base_url().'group');
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(base_url().'group');
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('name', 'name', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Group.php */
/* Location: ./application/controllers/Group.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-22 03:03:02 */
/* http://harviacode.com */