<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Classroom_model extends CI_Model
{

    public $table = 'classroom';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('classroom.id, classroom.name, classroom.quota, classroom.class_type_id, classroom.create_at, classroom.update_at, class_type.id type_id, class_type.name type_name');
        $this->db->from($this->table);
        $this->db->join('class_type','classroom.class_type_id=class_type.id');
        $this->db->where('classroom.id', $id);
        return $this->db->get()->row();
    }

    // get data by id
    function get_classroom_by_type($id)
    {
        $this->db->select('classroom.id, classroom.name, classroom.quota, classroom.class_type_id, classroom.create_at, classroom.update_at, class_type.id type_id, class_type.name type_name');
        $this->db->from($this->table);
        $this->db->join('class_type','classroom.class_type_id=class_type.id');
        $this->db->where('class_type.id', $id);
        return $this->db->get()->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('quota', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('quota', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Classroom_model.php */
/* Location: ./application/models/Classroom_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-22 18:08:58 */
/* http://harviacode.com */