<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Participants_model extends CI_Model
{

    public $table = 'participants';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_last_code()
    {
        $this->db->select('max(code) last_code');
        return $this->db->get($this->table)->row();
    }

    function get_count_participants($child_name, $phone)
    {
        $this->db->select('count(code) count');
        $this->db->where(array("LOWER(child_name)" => strtolower($child_name), "phone" => $phone));
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
    	$this->db->or_like('code', $q);
    	$this->db->or_like('child_name', $q);
    	$this->db->or_like('parent_name', $q);
    	$this->db->or_like('phone', $q);
    	$this->db->or_like('email', $q);
    	$this->db->or_like('address', $q);
    	$this->db->or_like('birth_date', $q);
    	$this->db->or_like('create_at', $q);
    	$this->db->or_like('update_at', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('code', $q);
    	$this->db->or_like('child_name', $q);
    	$this->db->or_like('parent_name', $q);
    	$this->db->or_like('phone', $q);
    	$this->db->or_like('email', $q);
    	$this->db->or_like('address', $q);
    	$this->db->or_like('birth_date', $q);
    	$this->db->or_like('create_at', $q);
    	$this->db->or_like('update_at', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Participants_model.php */
/* Location: ./application/models/Participants_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-24 00:41:54 */
/* http://harviacode.com */