<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Payment_model extends CI_Model
{

    public $table = 'payment';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all join
    function get_all_join($class_type, $classroom, $date, $pay_status)
    {
        $this->db->select('p.id, p.pay_status, p.create_at, p.update_at, r.reg_code, r.child_name, r.parent_name, r.phone, r.email, ct.name type_name, c.name class_name');
        $this->db->from('payment p');
        $this->db->join('register r','r.id=p.register_id');
        $this->db->join('classroom c','c.id=r.classroom_id');
        $this->db->join('class_type ct','c.class_type_id=ct.id');
        if ($class_type != null) {
            $this->db->where('ct.id', $class_type);
        }
        if ($classroom != null) {
            $this->db->where('c.id', $classroom);
        }
        if ($pay_status != null) {
            $this->db->where('p.pay_status', $pay_status);
        }
        // digunakan range tanggal 1 sampai 31 karena jumlah maks hari 31
        if ($date != null) { 
            $this->db->where('r.period >=', $date.'-01');
            $this->db->where('r.period <=', $date.'-31');
        }
        else {
            $this->db->where('r.period >=', date('Y-m').'-01');
            $this->db->where('r.period <=', date('Y-m').'-31');
        }
        $this->db->order_by('p.id', $this->order);
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('pay_status', $q);
	$this->db->or_like('register_id', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('pay_status', $q);
	$this->db->or_like('register_id', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data, $register_id)
    {
        // untuk update ke tabel payment
        $this->db->update($this->table, $data, array($this->id => $id));
        // untuk update ke tabel shipment
        $this->db->update('shipment', $data, array('register_id' => $register_id));
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Payment_model.php */
/* Location: ./application/models/Payment_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-24 16:56:46 */
/* http://harviacode.com */