<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Register_model extends CI_Model
{

    public $table = 'register';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('r.*, c.name class_name, ct.name class_type');
        $this->db->from('register r');
        $this->db->join('classroom c','c.id=r.classroom_id');
        $this->db->join('class_type ct','c.class_type_id=ct.id');
        $this->db->where('r.id', $id);
        return $this->db->get()->row();
    }

    function get_last_code()
    {
        $this->db->select('max(reg_code) last_code');
        return $this->db->get($this->table)->row();
    }

    function search_participants($value)
    {
        $this->db->like('child_name', $value , 'both');
        $this->db->order_by('child_name', 'ASC');
        $this->db->limit(10);
        return $this->db->get('participants')->result();
    }

    function get_count_book($class_book_id, $period)
    {
        $this->db->select('count(reg_code) count');
        $this->db->where(array("classroom_id" => $class_book_id, "DATE_FORMAT(birth_date,'%Y-%m')" => $period));
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('reg_code', $q);
	$this->db->or_like('child_name', $q);
	$this->db->or_like('parent_name', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('address', $q);
	$this->db->or_like('birth_date', $q);
	$this->db->or_like('period', $q);
	$this->db->or_like('class_type_id', $q);
	$this->db->or_like('classroom_id', $q);
	$this->db->or_like('note', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('reg_code', $q);
	$this->db->or_like('child_name', $q);
	$this->db->or_like('parent_name', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('address', $q);
	$this->db->or_like('birth_date', $q);
	$this->db->or_like('period', $q);
	$this->db->or_like('class_type_id', $q);
	$this->db->or_like('classroom_id', $q);
	$this->db->or_like('note', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        $insert_id = $this->db->insert_id();
        return  $insert_id;
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Register_model.php */
/* Location: ./application/models/Register_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-24 00:42:02 */
/* http://harviacode.com */