<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Shipment_model extends CI_Model
{

    public $table = 'shipment';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_count()
    {
        $this->db->select('id');
        $this->db->where('pay_status',1);
        $this->db->where('ship_status',1);
        return $this->db->count_all_results($this->table);
    }

    // get all join
    function get_all_join($class_type, $classroom, $date, $ship_status)
    {
        $this->db->select('r.id reg_id, s.id, s.pay_status, s.ship_status, s.create_at, s.update_at, r.reg_code, r.child_name, r.parent_name, r.phone, r.email');
        $this->db->from('shipment s');
        $this->db->join('register r','r.id=s.register_id');
        $this->db->join('classroom c','c.id=r.classroom_id');
        $this->db->join('class_type ct','c.class_type_id=ct.id');
        $this->db->where('s.pay_status',1);
        if ($class_type != null) {
            $this->db->where('ct.id', $class_type);
        }
        if ($classroom != null) {
            $this->db->where('c.id', $classroom);
        }
        if ($ship_status != null) {
            $this->db->where('s.ship_status', $ship_status);
        }
        // digunakan range tanggal 1 sampai 31 karena jumlah maks hari 31
        if ($date != null) { 
            $this->db->where('r.period >=', $date.'-01');
            $this->db->where('r.period <=', $date.'-31');
        }
        else {
            $this->db->where('r.period >=', date('Y-m').'-01');
            $this->db->where('r.period <=', date('Y-m').'-31');
        }
        $this->db->order_by('s.id', $this->order);
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('pay_status', $q);
	$this->db->or_like('ship_status', $q);
	$this->db->or_like('register_id', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('pay_status', $q);
	$this->db->or_like('ship_status', $q);
	$this->db->or_like('register_id', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // update data by register_id
    function update_by_register_id($id, $data)
    {
        $this->db->where('register_id', $data->register_id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Shipment_model.php */
/* Location: ./application/models/Shipment_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-26 07:51:07 */
/* http://harviacode.com */