<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_model extends CI_Model
{

    public $table = 'user';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function get_count()
    {
      return $this->db->count_all_results($this->table);
    }

    function cek_login($where){      
        return $this->db->get_where($this->table,$where);
    }

    function exist_row_check($table,$field,$data){
        $this->db->where($field,$data);
        $this->db->from($table);
        $query = $this->db->get();
        return $query->num_rows();
    }

    // get data by id
    function get_by_username($username)
    {
        $this->db->where('username', $username);
        return $this->db->get($this->table)->row();
    }

    // get all
    function get_all()
    {
        $this->db->select('user.id as id,user.name,user.username,user.group_id,group.name as group,user.create_at,user.update_at');
        $this->db->join('group', 'group.id=user.group_id');
        $this->db->order_by('name', 'ASC');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('user.*,group.name as group');
        $this->db->join('group', 'group.id=user.group_id');
        $this->db->where('user.id', $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file User_model.php */
/* Location: ./application/models/User_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-22 02:24:38 */
/* http://harviacode.com */